# Generated by Django 4.2.23 on 2025-07-09 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Commercial name of the medicine', max_length=200)),
                ('formula', models.CharField(help_text='Active ingredient or formula', max_length=200)),
                ('dose', models.CharField(help_text='Dosage and packaging information', max_length=200)),
                ('manufacturer', models.CharField(help_text='Manufacturer name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in British pounds', max_digits=10)),
                ('rating', models.FloatField(help_text='Customer/clinical rating out of 5 (Demo only)')),
                ('emc_leaflet_url', models.URLField(blank=True, help_text='URL to the EMC patient leaflet for this medicine', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_uk_meds.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sample_uk_meds.order')),
            ],
        ),
    ]
