# Generated by Django 4.2.23 on 2025-07-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_uk_meds', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='common_usage',
            field=models.CharField(blank=True, help_text='Short summary of what the medicine is commonly used for (e.g. headache, cold & flu)', max_length=255),
        ),
    ]
